$schema: https://cdn.jsdelivr.net/npm/@micro-lc/interfaces@latest/schemas/v2/config.schema.json
version: 2

layout:
  sources: http://localhost:8000/packages/layout/dist/mlc-layout.js
  content:
    - tag: mlc-layout
      properties:
        mode: topBar
        logo:
          url: https://avatars.githubusercontent.com/u/92730708?s=200&v=4
        menuItems:
          - icon:
              library: '@ant-design/icons-svg'
              selector: GlobalOutlined
            id: wiki
            label: Wikipedia
            type: application

applications:
  wiki:
    integrationMode: iframe
    route: /
    src: https://www.wikipedia.org/
    attributes:
      title: Wikipedia
