version: '3'

services:
  reverse-proxy:
    networks:
      - ring
    ports:
      - 80:8080
    image: nginx:1.23.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
        - host.docker.internal:host-gateway
  back-kit:
    image: microlc/bk-web-components:${BACK_KIT_VERSION:-1.1.0}
    ports:
      - 8080:8080
    networks:
        - ring

networks:
    ring:
