$schema: https://cdn.jsdelivr.net/npm/@micro-lc/interfaces@latest/schemas/v2/config.schema.json
version: 2

settings:
  defaultUrl: ./

layout:
  sources: https://cdn.jsdelivr.net/npm/@micro-lc/layout@latest/dist/mlc-layout.js
  content:
    - tag: mlc-layout
      properties:
        mode: topBar
        logo:
          url: https://avatars.githubusercontent.com/u/92730708?s=200&v=4
      content:
        tag: div
        content: Mount anything here!
        attributes:
          slot: top-bar

applications:
  orders:
    integrationMode: compose
    route: ./
    config:
      content:
        - tag: div
          attributes:
            class: content
