name: Main

env:
  context: './'
  cache-name: cache-release
  NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  node-version: 16.x

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  prepare:
    uses: micro-lc/micro-lc/.github/workflows/prepare.yml@main

  checks:
    needs:
      - prepare
    uses: micro-lc/micro-lc/.github/workflows/checks.yml@main


  unit-tests:
    needs:
      - prepare
    uses: micro-lc/micro-lc/.github/workflows/unit-tests.yml@main

  e2e-tests:
    needs:
      - prepare
    uses: micro-lc/micro-lc/.github/workflows/e2e-tests.yml@main

  release-docker:
    needs:
      - checks
      - unit-tests
      - e2e-tests
    if: ${{ startsWith(github.ref, 'refs/heads/main') }}
    uses: micro-lc/micro-lc/.github/workflows/release-docker.yml@main
    with:
      version: latest
    secrets:
      username: ${{ secrets.BOT_DOCKER_USERNAME }}
      token: ${{ secrets.BOT_DOCKER_TOKEN }}
