name: Main PR

env:
  context: './'
  cache-name: cache-release
  NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  node-version: 16.x

on:
  pull_request:
    branches:
      - main

jobs:
  install:
    uses: micro-lc/micro-lc-2.0/.github/workflows/install.yml@main

  # checks:
  #   needs:
  #     - install
  #   uses: micro-lc/micro-lc-2.0/.github/workflows/checks.yml@main

  build:
    needs:
      - install
    uses: micro-lc/micro-lc-2.0/.github/workflows/build.yml@main

  tests:
    needs:
      - install
    strategy:
      fail-fast: false
      matrix:
        package:
          - iconic
          - interfaces
          - composer
          - orchestrator

    uses: micro-lc/micro-lc-2.0/.github/workflows/tests.yml@main
    with:
      package: ${{ matrix.package }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
