name: Main

env:
  context: './'
  cache-name: cache-release
  NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  node-version: 16.x

on:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    uses: micro-lc/micro-lc/.github/workflows/prepare.yml@main

  checks:
    needs:
      - prepare
    uses: micro-lc/micro-lc/.github/workflows/checks.yml@main

  unit-tests:
    needs:
      - prepare
    uses: micro-lc/micro-lc/.github/workflows/unit-tests.yml@main

  e2e-tests:
    needs:
      - prepare
    uses: micro-lc/micro-lc/.github/workflows/e2e-tests.yml@main
