name: Docker container release

on:
  workflow_call:
    inputs:
      node-version:
        default: 16.x
        required: false
        type: string
      version:
        required: true
        type: string
    secrets:
      username:
        required: true
      token:
        required: true

jobs:
  release-docker:
    name: Build web-server docker container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Build
        run: yarn initialize --cleanup orchestrator

      - name: Prepare
        id: prepare-docker-container
        run: |
          DOCKER_IMAGE=microlc/micro-lc
          echo "tag=${DOCKER_IMAGE}:${{ inputs.version }}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./.docker/Dockerfile
          build-args: |
            COMMIT_SHA=${GITHUB_SHA}
            DESCRIPTION="The Mia-Platform micro frontend solution"
            VERSION=${VERSION}
          pull: true
          push: true
          tags: ${{ steps.prepare-docker-container.outputs.tag }}
