name: tag CI

env:
  context: './'
  cache-name: cache-release
  node-version: 16.x

on:
  push:
    tags:
      - '*'

jobs:
  pack:
    name: Build web-server docker container
    # needs: test
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=microlc/micro-lc
          VERSION=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            VERSION=$(echo ${VERSION} | sed s/^v//)
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            VERSION=latest
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=image::${DOCKER_IMAGE}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.BOT_DOCKER_USERNAME }}
      #     password: ${{ secrets.BOT_DOCKER_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: '${{ env.context }}.docker'
      #     push: true
      #     tags: ${{ steps.prepare.outputs.tags }}
