name: Node.js ui-components CI

env:
  context: ./packages/ui-components/

on:
  push:
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn ui-components install --frozen-lockfile
      - run: yarn ui-components coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "${{ env.context }}coverage/lcov.info"
          base-path: "${{ env.context }}"
      - name: Compile file and build
        run: yarn ui-components build
      - name: Get tagged version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Update ui-components version
        run: yarn ui-components version --no-git-tag-version --no-commit-hooks --new-version "${{ steps.get_version.outputs.VERSION }}"
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: './packages/ui-components/package.json'
          access: 'public'
          token: ${{ secrets.NPM_TOKEN }}
