name: Node.js ui-components CI

env:
  context: ./packages/ui-components/

on:
  push:
    tags:
      - 'v1**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn ui-components install --frozen-lockfile
      - run: yarn ui-components coverage

      - name: Compile file and build
        run: yarn ui-components build
      - uses: JS-DevTools/npm-publish@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          package: './packages/ui-components/package.json'
          access: 'public'
          token: ${{ secrets.NPM_TOKEN }}
